name: transformers
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy=2.3.0
  - tiktoken=0.11.0
  - datasets=3.2.0
  - wandb=0.22.0
  - pip
  - pip:
      - torch==2.7.0 --index-url https://download.pytorch.org/whl/cu128
